import time
print("-----WELCOME TO THE TUPLE TO LIST CONVERTER-----")
time.sleep(2)
fn=input("First Name: ")
time.sleep(1)
ln=input("Last Name: ")
time.sleep(1)
A=input("Age: ")
time.sleep(1)
h=input("Height: ")
time.sleep(1)
w=input("Weight: ")
time.sleep(1)
fs=input("Favorite Subject: ")
time.sleep(1)
print("Converting tuple to list...")
time.sleep(2.5)
mytuple = (fn, ln, A, h, w, fs)
mylist = list(mytuple)
print("1. ",mylist[0])
time.sleep(0.5)
print("2. ",mylist[1])
time.sleep(0.5)
print("3. ",mylist[2])
time.sleep(0.5)
print("4. ",mylist[3])
time.sleep(0.5)
print("5. ",mylist[4])
time.sleep(0.5)
print("6. ",mylist[5])
print("Tuple converted to list successfully!")
time.sleep(1)
print("Thank you for using the Tuple to List Converter!")